jobs:
  ci:
    name: Ci
    runs-on: ubuntu-20.04

    steps:
      - name: Pull
        uses: actions/checkout@v2
      - name: Get Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./run/ci

name: Run

on:
  schedule:
    - cron: "40 */2 * * *"
